num_years_investigate: 20

start_month_investigate: 7         # If want to start investigation not in January
start_year_investigate: 2023

prehouse_rent_monthly: 2500                # rent cost per month , put 0 here if you are couch-surfing
                                           # until you buy the house!
housePurchase_month_investigate: 1
housePurchase_year_investigate: 2025

verbose: 1


##############################
### Current net-worth settings
##############################
# These are tracked to help compute your net worth
current_savings: 100_000          # current savings in bank account
current_investments: 100_000       # current investments in brokerage account
current_k401: 0                   # current 401k balance
current_roth: 0                   # current roth balance



##############################
### Salary settings
##############################
base_salary : 100_000
signon_bonus : 50_000
total_rsus : 200_000             # uses 25% investing schedule per year over 4 years

annual_investment_appreciation: 0.07    # average investment appreciation

##############################
### Housing settings
##############################

###############
### Option 1: Renting
###############
rent_monthly: 2500                # rent cost per month
rental_insurance_monthly: 17      # rental insurance per month

###############
## Option 2: Mortgage
###############
house_cost: 300_000                   # property value bought at
house_appreciation_annual_rate: 0.04  # house appreciation rate per year

amount_down: 20_000                # amount down for loan
loan_duration: 15                 # loan duration in years
loan_interest_rate:               # interest rate for loan for each loan duration
  # year : interest rate
  10: 6.5                         # Current interest rate breakdown according to bank I am intersted in
  15: 5.875
  20: 6.375
  30: 6.750
## monthly fees
pmi_monthly: 180.
property_tax_monthly: 220         # property tax per month
hoa_fee_monthly: 344              # HOA fee per month
home_insurance_monthly: 87        # home insurance per month
## sales costs
agent_sales_cost: 6.0             # agent sales cost in percentage
docs_stamp_cost:  0.7             # docs stamp cost in percentage
title_ins_cost:   0.7             # title insurance cost in percentage
# extra payments
onetime_extra_payment:
  # month : amount paid on that month
  0: 0
  12: 0
monthly_extra_payment:
  # month : amount paid every month starting on that month until next setting
  0: 0

# extra money made renting out the house or a spare room (e.g. airbnb, etc.)
mortgage_renting_income_monthly: 0

## utilities costs
utilities_monthly: 300            # e.g. water, electricity, gas, internet, etc.

##############################
### Food & Entertainment settings
##############################
medicare_tax_annual: 5000         # 



##############################
### Food & Entertainment settings
##############################
foodandentertainment_monthly: 1000  # adapt this to your lifestyle
                                    # groceries, eating out, entertainment, etc.




##############################
### Retirement settings
##############################
k401:  22_500                           # intended 401k contribution per year
k401_company_coverage: 11_250                # company match for 401k

roth: 6500                              # intended roth contribution per year




##############################
### Banking settings
##############################
savings_interest_rate: 0.04       # interest rate for savings account

